config/routes.rb
Cryosearch::Application.routes.draw do
  resources :protocols

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/protocol.rb
class Protocol < ActiveRecord::Base
  attr_accessible :cell_or_tissue_type, :title, :description, :genus, :species, :user_id, :materials, :references, :instructions
  
  validates :cell_or_tissue_type, :title, :description, :genus, :species, :user_id, :materials, :references, :instructions, :presence => true


  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
end

app/models/user.rb
class User < ActiveRecord::Base
	rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :confirmed_at

  has_many :protocols
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @protocols = Protocol.all
  end
end

app/controllers/protocols_controller.rb
class ProtocolsController < ApplicationController
  before_filter :authenticate_user!
  # GET /protocols
  # GET /protocols.json
  def index
    @protocols = Protocol.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @protocols }
    end
  end

  # GET /protocols/1
  # GET /protocols/1.json
  def show
    @protocol = Protocol.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @protocol }
    end
  end

  # GET /protocols/new
  # GET /protocols/new.json
  def new
    @protocol = Protocol.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @protocol }
    end
  end

  # GET /protocols/1/edit
  def edit
    @protocol = Protocol.find(params[:id])
  end

  # POST /protocols
  # POST /protocols.json
  def create
    @protocol = Protocol.new(params[:protocol])

    respond_to do |format|
      if @protocol.save
        format.html { redirect_to @protocol, notice: 'Protocol was successfully created.' }
        format.json { render json: @protocol, status: :created, location: @protocol }
      else
        format.html { render action: "new" }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /protocols/1
  # PUT /protocols/1.json
  def update
    @protocol = Protocol.find(params[:id])

    respond_to do |format|
      if @protocol.update_attributes(params[:protocol])
        format.html { redirect_to @protocol, notice: 'Protocol was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @protocol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /protocols/1
  # DELETE /protocols/1.json
  def destroy
    @protocol = Protocol.find(params[:id])
    @protocol.destroy

    respond_to do |format|
      format.html { redirect_to protocols_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/protocols_helper.rb
module ProtocolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class='row'>
  <div class='span3'>
    <img  src="http://placehold.it/250x150" alt="CryoSearch">
  </div>
  <div class="span9">
    <h1 id="cryosearch">Find the Protocol You Need. Fast.</h1>
    <p>Twee wolf pork belly bicycle rights. Umami selvage high life skateboard sartorial, mumblecore street art. Echo park hoodie post-ironic mumblecore beard umami. Biodiesel you probably haven't heard of them odd future fap. Chillwave williamsburg whatever four loko seitan sriracha. Hoodie before they sold out 8-bit ethical bicycle rights wayfarers. Fingerstache seitan cosby sweater artisan.</p>
<p class="pull-right">    Not a member yet? <%= link_to 'Sign up', new_user_registration_path, :class => 'btn btn-primary' %>
</p>    
  </div>
</div>

<div class='row'>
  <div class='span4'>
    <h2>Latest Protocols</h2>
    <% @protocols.each do |p| %>
      <li>
        <em><%= link_to "#{p.genus} #{p.species}", p %></em> added on <%= p.created_at.to_date %>
      </li>
    <% end %>
  </div>
  <div class='span4'>
    <h2>Popular Protocols</h2>
    <% @protocols.each do |p| %>
      <li>
        <em><%= link_to "#{p.genus} #{p.species}", p %></em> added on <%= p.created_at.to_date %>
      </li>
    <% end %>
  </div>
  <div class='span4'>
    <h2>Add a Protocol</h2>
      <a class="btn btn-primary btn-large" href="/protocols/new"><i class="icon-plus-sign"></i> Submit a protocol</a>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Cryosearch", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cryosearch" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/protocols/_form.html.erb
<script type="text/javascript">
(function($) {
	$(document).ready(function() {
		$('.wysiwyg').redactor({
		  css: '../redactor-form.css',
		  buttons: ['html', '|', 'formatting', '|', 'bold', 'italic', 'deleted', '|',
      'unorderedlist', 'orderedlist', 'outdent', 'indent', '|',
      'image', 'video', 'table', 'link', '|',
      'alignleft', 'aligncenter', 'alignright', 'justify', '|',
      'horizontalrule', 'fullscreen']
		
		});
	  // $('#protocol_description').redactor();
	 //  $('#protocol_description').redactor();
	});
})(jQuery);
</script>

<%= simple_form_for(@protocol) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class='span12'>
        <%= f.input :title %>
      </div>
    </div>
    <div class='row'>
      <div class='span4'>    <%= f.input :genus %></div>
      <div class='span4'>    <%= f.input :species %></div>
      <div class='span4'>    <%= f.input :cell_or_tissue_type %></div>
    </div>
    <div class='row'>
      <div class='span4'>
        <%= f.input :materials, :input_html => {:class => 'wysiwyg'} %>    
      </div>  
      <div class='span8'>  
        <%= f.input :description, :input_html => {:class => 'wysiwyg'} %>
      </div>
    </div>
    <div class='row'>
      <div class='span12'>
        <%= f.input :instructions, :name => "Protocol", :input_html => {:class => 'wysiwyg'}  %>
        <%= f.input :references, :input_html => {:class => 'wysiwyg'} %>        
      </div>
    </div>


    <%= f.input :user_id, :as => :hidden, :input_html =>  {:value => current_user.id} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :value => 'Save' %>
  </div>
<% end %>

app/views/protocols/edit.html.erb
<h1><small>Edit details for</small> <em><%= @protocol.genus %> <%= @protocol.species %></em></h1>

<%= render 'form' %>

app/views/protocols/index.html.erb
<h1>Listing protocols</h1>

<table>
  <tr>
    <th>Genus</th>
    <th>Species</th>
    <th>Cell or tissue type</th>
    <th>Description</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @protocols.each do |protocol| %>
  <tr>
    <td><%= protocol.genus %></td>
    <td><%= protocol.species %></td>
    <td><%= protocol.cell_or_tissue_type %></td>
    <td><%= protocol.description %></td>
    <td><%= protocol.user_id %></td>
    <td><%= link_to 'Show', protocol %></td>
    <td><%= link_to 'Edit', edit_protocol_path(protocol) %></td>
    <td><%= link_to 'Destroy', protocol, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Protocol', new_protocol_path %>

app/views/protocols/new.html.erb
<h1>New protocol</h1>

<%= render 'form' %>

<%= link_to 'Back', protocols_path %>

app/views/protocols/show.html.erb
<h1>

  <em><%= @protocol.genus %>
  <%= @protocol.species %> (<%= @protocol.cell_or_tissue_type %>)</em>
</h1>
<div class='row'>
  <div class="span12">
    <small>(<%= @protocol.title %>)</small>
  </div>
  </div>
  
<div class='row'>
  <div class='span12'>
    <h3>Intro/Description:</h3>
    <p><%= simple_format(@protocol.description) %></p>
  </div>
</div>
<div class='row'>
  <div class='span12'>
    <h3>Materials:</h3>
    <p><%= simple_format(@protocol.materials) %></p>

  </div>
</div>
<div class='row'>
  <div class='span12'>
    <h3>Protocol:</h3>
      <p><%= simple_format(@protocol.instructions) %></p> 
  </div>
</div>
<div class='row'>
  <div class='span12'>
    <h3>References:</h3>
      <p><%= simple_format(@protocol.references) %></p> 
  </div>
</div>
<div class='row'>
  <div class='span12'>
    <b>Added by:</b> <%= @protocol.user.email %>
  </div>
</div>


<% if current_user %>
<%= link_to 'Edit', edit_protocol_path(@protocol) %> |
<%= link_to 'Back', protocols_path %>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>